// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDadhOTwZMWTQqZMkvOUqoXccJ817rpWSM',
    appId: '1:740287217421:web:717c5286a69ba354b83a44',
    messagingSenderId: '740287217421',
    projectId: 'guestportal-de002',
    authDomain: 'guestportal-de002.firebaseapp.com',
    storageBucket: 'guestportal-de002.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB7svWCNY-RxEeMZjgDnIY02_bruHQlZ8A',
    appId: '1:740287217421:android:39d8bf8c94e205d9b83a44',
    messagingSenderId: '740287217421',
    projectId: 'guestportal-de002',
    storageBucket: 'guestportal-de002.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAq0VgJ7pTdIW2_b2EOVTDaITOlrh2OkEM',
    appId: '1:740287217421:ios:50fdfad6f5fcb0d8b83a44',
    messagingSenderId: '740287217421',
    projectId: 'guestportal-de002',
    storageBucket: 'guestportal-de002.appspot.com',
    iosClientId:
        '740287217421-q1585ojuoi4ussu1bhb0o8rd1g3d9if1.apps.googleusercontent.com',
    iosBundleId: 'com.example.day59',
  );
}
